### ISSUE TITLE
Damage tracking issues

### ISSUE THREAD

**Issue by tiosgz** [buffet/kiwmi#38]
I don’t expect damage tracking to be perfect yet, just leaving here some early feedback.

- [ ] screenshots, only applicable very soon after starting kiwmi (although I’m writing about two outputs, it’s reproducible with one as well)
  - they have one or both outputs filled with black
  - after taking a screenshot and until new damage, some outputs flicker between black and their ‘normal’ buffer
- [x] layer shell updates seem to be ignored
- [x] popups (and subsurfaces?) are mostly ignored (I have a PR (edit: #39) in the works that targets them, so if it doesn’t take me too long I’ll try to add the damage tracking bits to it)

from later comments:
- [ ] nothing is drawn after switching to a tty and back

---

testcases:

- screenshots
  1. start kiwmi anew
  2. take a screenshot (I have `Print` bound to something like `grim ~/grim.png`, in case it matters)
  3. all outputs start flickering (because they haven’t been updated many times yet?)
  4. spawn something (in case it’s layer-shell, only its output will be affected, as you can expect)
  5. all outputs are okay
  6. check the screenshot – it’s black
- layer shell
  1. open an app that reacts to mouse movement
  2. spawn wofi
  3. type something
  4. the list is still as initially
  5. move the mouse so that the app updates
  6. wofi finally updates
- popups/subsurfaces
  1. open an app that has a menu
  2. open the menu with the keyboard
  3. the menu either doesn’t show, flickers, or shows 🤷
  4. navigate the menu with the up/down arrow keys
  5. it doesn’t update
  6. move the mouse over the menu
  7. it updates

**Comment by buffet** [comment]
Layer shell should be fixed; popups and subsurfaces are complete ignored right now (should be unrelated to damage tracking).

I'll look into the screenshot stuff.

**Comment by buffet** [comment]
It also doesn't redraw after switching ttys back to it.

**Comment by 6gk** [comment]
i am sorry but i didn't subscribe to this repository to actually get emails!

kidding, love your work tio <3
